# Nombre del workflow que aparecerá en la pestaña Actions
name: Crear Repositorio para Estudiante

# Permisos que el GITHUB_TOKEN necesita para ejecutar las tareas
permissions:
  contents: write  # Para crear repositorios en la organización
  issues: write    # Para poder comentar en el issue que disparó la acción

# Evento que dispara este workflow
on:
  issues:
    types: [opened] # Se ejecuta solo cuando se abre un nuevo issue

# Definición de los trabajos (jobs) que se ejecutarán
jobs:
  create-repo:
    # Condición para ejecutar este job: el título del issue DEBE empezar con la frase exacta
    if: startsWith(github.event.issue.title, 'Crear mi repositorio')

    # Especificación explícita del runner para evitar que se quede en cola
    runs-on:
      group: Standard GitHub-hosted runners
      labels: ubuntu-latest

    # Pasos que se ejecutarán dentro del job
    steps:
      - name: Crear Repositorio y Asignar Colaborador
        env:
          # El GITHUB_TOKEN es proporcionado automáticamente por GitHub Actions
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Nombre de la organización donde se creará el repo
          ORG_NAME: "UPTPC"
          # Nombre de usuario de la persona que abrió el issue
          STUDENT_USERNAME: ${{ github.event.issue.user.login }}
          # Número del issue para poder comentar en él
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          # Extraemos el título del proyecto del issue, quitando el prefijo "Crear mi repositorio "
          PROJECT_TITLE=$(echo "${{ github.event.issue.title }}" | sed 's/Crear mi repositorio //')

          # Si el título era solo "Crear mi repositorio" (sin nada más), usamos "proyecto" como nombre base.
          if [ -z "$PROJECT_TITLE" ] || [ "$PROJECT_TITLE" == "Crear mi repositorio" ]; then
            PROJECT_TITLE="proyecto"
          fi
          
          # Reemplazamos espacios por guiones para un nombre de repo válido
          REPO_NAME_SLUG=$(echo "$PROJECT_TITLE" | tr ' ' '-')

          # Creamos el nombre final del repositorio combinando el título y el nombre de usuario
          REPO_NAME="${REPO_NAME_SLUG}-${STUDENT_USERNAME}"

          echo "Creando repositorio llamado: $REPO_NAME para el usuario: $STUDENT_USERNAME"

          # 1. Crear el repositorio en la organización usando la CLI oficial de GitHub
          gh repo create "${ORG_NAME}/${REPO_NAME}" --public --description "Repositorio para el proyecto de ${STUDENT_USERNAME}"

          # 2. Añadir al estudiante como colaborador con permisos de escritura (push)
          gh repo collaborator add "${ORG_NAME}/${REPO_NAME}" "${STUDENT_USERNAME}" --permission push

          # 3. Comentar en el issue para notificar que el repositorio se ha creado
          REPO_URL="https://github.com/${ORG_NAME}/${REPO_NAME}"
          COMMENT_BODY="¡Felicidades @${STUDENT_USERNAME}! Tu repositorio **${REPO_NAME}** ha sido creado exitosamente. Puedes acceder a él aquí: ${REPO_URL}"
          gh issue comment "${ISSUE_NUMBER}" --body "$COMMENT_BODY"
