name: Crear Repositorio para Estudiante

on:
  issues:
    types: [opened]

permissions:
  contents: write
  issues: write
  pull-requests: write
  repository-projects: write

jobs:
  create-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar título del Issue
        if: github.event.issue.title != 'Crear mi repositorio'
        run: exit 1  # Falla si el título no coincide

      - name: Crear Repositorio
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.event.issue.user.login }}
        run: |
          REPO_NAME="proyecto-$GITHUB_USERNAME"
          # 1. Crear repositorio
          curl -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"name":"'"$REPO_NAME"'", "private":false}' \
            https://api.github.com/orgs/UPTPC/repos

          # 2. Añadir colaborador
          curl -X PUT \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"permission":"push"}' \
            https://api.github.com/repos/UPTPC/$REPO_NAME/collaborators/$GITHUB_USERNAME

          # 3. Notificar en el issue
          curl -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"body":"¡Repositorio creado! Accede aquí: https://github.com/UPTPC/'"$REPO_NAME"'"}' \
            https://api.github.com/repos/UPTPC/proyecto-automatizacion/issues/${{ github.event.issue.number }}/comments
