name: Crear Repositorio para Estudiante

on:
  issues:
    types: [opened]

jobs:
  create-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar el título del Issue
        if: github.event.issue.title == 'Crear mi repositorio'
        run: echo "Titulo OK. Iniciando la creación del repositorio..."

      - name: Crear Repositorio
        if: github.event.issue.title == 'Crear mi repositorio'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.event.issue.user.login }}
        run: |
          REPO_NAME="proyecto-${GITHUB_USERNAME}"
          # Crea el repositorio en la organización
          curl -X POST \
          -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/orgs/UPTPC/repos \
          -d "{\"name\":\"$REPO_NAME\"}"
          # Asigna permisos de escritura al estudiante
          curl -X PUT \
          -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/UPTPC/$REPO_NAME/collaborators/$GITHUB_USERNAME \
          -d '{"permission":"push"}'
          # Comentar en el issue para notificar al estudiante
          curl -X POST \
          -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/UPTPC/proyecto-automatizacion/issues/${{ github.event.issue.number }}/comments \
          -d "{\"body\":\"¡Tu repositorio ha sido creado! Puedes encontrarlo en https://github.com/UPTPC/$REPO_NAME\"}"
